### PR TITLE
update to 3.0.2

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @msarahan

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks @ocefpaf - I hope this helps clear up some of the stuff people are seeing.  Has conda-verify been causing many issues?  I'm actually very happy that CF is using it.  We've been afraid to update our package to 3.0.  Since conda-build has it turned on by default, and since 2.0 did nothing due to a packaging error, we didn't want to suddenly start failing recipes all over the place when people thought they were OK (especially if the results were false positives!)

**Comment by ocefpaf** [comment]
> Has conda-verify been causing many issues?

Minor issues with version 3.0.1 but I removed it from the channel. We had version 2.0.0 for a while and everything was fine BTW.

>  I'm actually very happy that CF is using it.

Hopefully it will help us improve the interoperability of conda-forge and defaults recipes.

**Comment by msarahan** [comment]
Heh, version 2.0 did absolutely nothing.  Setup.py didn't actually include any of the meaningful checks.  So, it worked fine in testing, but our package was essentially no-op.

Keep me posted if there are any issues with 3.0.2.  With you all blazing the trail, I'll feel better about putting it on defaults, too.

**Comment by ocefpaf** [comment]
> Heh, version 2.0 did absolutely nothing.

:smile:

> Keep me posted if there are any issues with 3.0.2. With you all blazing the trail, I'll feel better about putting it on defaults, too.

Will do.

**Pull request merged**
